### ISSUE TITLE
Add an option to validate query parameters

### ISSUE THREAD

**Issue by arjupba** [dbartholomae/middy-middleware-class-validator#27]

**Comment by dbartholomae** [comment]
Happy about a PR contribution! :)

**Comment by arjupba** [comment]
> Happy about a PR contribution! :)

Let me check.

**Comment by arjupba** [comment]
Hi @dbartholomae ,

I've raised a PR for this issue.
Please have a look at it.

https://github.com/dbartholomae/middy-middleware-class-validator/pull/28

Thanks
