### ISSUE TITLE
Add options to pass validation options

### ISSUE THREAD

**Issue by arjupba** [dbartholomae/middy-middleware-class-validator#30]
It may be required to pass validation options like {whitelist: true}, in some scenario.

** Would you be willing to help with a PR? **

- [x] Yes, absolutely
- [ ] Yes, with some guidance
- [ ] Unfortunately no time :'-(

It can be fixed by adding extra parameters.

**Comment by dbartholomae** [comment]
Sure, maybe as `bodyOptions` and `queryOptions`?

**Comment by arjupba** [comment]
@dbartholomae yes, that works for me.
